config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :gifts do
    collection do
      get 'search'
    end
  end
  resources :items, except: :show do
    collection do
      get 'search'
    end
  end
  resources :interests do
    collection do
      get 'search'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gift.rb
class Gift < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :status
  validates :status_id, numericality: { other_than: 1, message: 'を選択してください' }

  validates :name, presence: true

  def self.search(search)
    if search != ''
      Gift.where('name LIKE(?) OR partner LIKE(?) OR event LIKE(?) OR memo LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%",
                 "%#{search}%")
    else
      Gift.all
    end
  end
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :name, presence: true

  def self.search(search)
    if search != ''
      Interest.where('name LIKE(?) OR memo LIKE(?)', "%#{search}%", "%#{search}%")
    else
      Interest.all
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :user

  validates :name, presence: true

  def self.search(search)
    if search != ''
      Item.where('name LIKE(?) OR memo LIKE(?) OR shop LIKE(?) OR shopinfo LIKE(?)', "%#{search}%", "%#{search}%", "%#{search}%",
                 "%#{search}%")
    else
      Item.all
    end
  end
end

app/models/status.rb
class Status < ActiveHash::Base
  self.data = [
    { id: 1, name: '選択してください(もらった物 or 贈った物)' },
    { id: 2, name: 'もらった物' },
    { id: 3, name: '贈った物' }
  ]

  include ActiveHash::Associations
  has_many :gifts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :gifts
  has_many :interests
  has_many :items

  validates :password, format: { with: /\A[a-zA-Z0-9]+\z/, message: 'は半角英数字のみ入力可です' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end
end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_gift, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def index
    @gifts = Gift.includes(:user).order('event_date DESC')
  end

  def new
    @gift = Gift.new
  end

  def create
    @gift = Gift.create(gift_params)
    if @gift.save
      redirect_to gifts_path
    else
      render :new
    end
  end

  def show
    @gift = Gift.find(params[:id])
  end

  def edit
  end

  def update
    if @gift.update(gift_params)
      redirect_to gift_path(@gift.id)
    else
      render :edit
    end
  end

  def destroy
    @gift.destroy
    redirect_to gifts_path
  end

  def search
    @gifts = Gift.search(params[:keyword]).order('event_date DESC')
  end

  private

  def gift_params
    params.require(:gift).permit(:status_id, :name, :image, :partner, :event_date, :event, :memo).merge(user_id: current_user.id)
  end

  def set_gift
    @gift = Gift.find(params[:id])
  end

  def correct_user
    redirect_to gifts_path unless current_user.id == @gift.user_id
  end
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_interest, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  def index
    @interests = Interest.includes(:user).order('created_at DESC')
  end

  def new
    @interest = Interest.new
  end

  def create
    @interest = Interest.create(interest_params)
    if @interest.save
      redirect_to interests_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @interest.update(interest_params)
      redirect_to interest_path(@interest.id)
    else
      render :edit
    end
  end

  def destroy
    @interest.destroy
    redirect_to interests_path
  end

  def search
    @interests = Interest.search(params[:keyword]).order('created_at DESC')
  end

  private

  def interest_params
    params.require(:interest).permit(:name, :image, :price, :memo).merge(user_id: current_user.id)
  end

  def set_interest
    @interest = Interest.find(params[:id])
  end

  def correct_user
    redirect_to interests_path unless current_user.id == @interest.user_id
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search]
  before_action :if_not_admin, except: [:index, :search]
  before_action :set_item, only: [:edit, :update, :destroy]

  def index
    @items = Item.includes(:user).order('created_at DESC')
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.create(item_params)
    if @item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to items_path
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  def search
    @items = Item.search(params[:keyword]).order('created_at DESC')
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :price, :memo, :shop, :shopinfo).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/gifts/_form.html.erb
<%= form_with(model: gift, local: true) do |f| %>
  
  <%= render 'layouts/error_messages', model: f.object %>

  <%= f.collection_select(:status_id, Status.all, :id, :name, {}, {class:"status-select"}) %>
  <%= f.text_field :name, placeholder: "ギフトの名称" %>
  <%= f.file_field :image %>
  <div id="image-list"></div>
  <%= f.text_field :partner, placeholder: "相手未入力" %>
  <%= f.date_field :event_date, use_month_numbers: true, class:"date_form" %>
  <%= f.text_field :event, placeholder: "イベント未入力" %>
  <%= f.text_area :memo, placeholder: "メモ", rows: "10" %>
  <%= f.submit "登録" %>

<% end %>

app/views/gifts/_gift.html.erb
<% if current_user.id == gift.user_id %>
<div class="content_post">
  <%= link_to gift_path(gift.id), class: "sub" do %>
    <%= image_tag gift.image.variant(resize: '400x400'), class: 'gift-image' if gift.image.attached? %>
    <div class="side">
      <% if gift.status_id == 2 %>
        <div class="status_a"><%= gift.status.name %></div>
      <% else %>
        <div class="status_b"><%= gift.status.name %></div>
      <%end%>
      <div><strong><%= gift.name %></strong></div>  
      <div><%= gift.partner %></div>
      <div><%= gift.event_date&.strftime('%Y/%m/%d') %>
      <div><%= gift.event %></div>  
    </div>
  <% end %>
</div>
<% end %>

app/views/gifts/edit.html.erb
<div class="contents row">
  <div class="container">
    <h2>編集</h2>
    <%= render partial: "form", locals: { gift: @gift } %>    
  </div>
</div>

app/views/gifts/index.html.erb
<div class="contents row">
  <p class="sub_title">ギフト記録</p>
  <%= form_with(url: search_gifts_path, method: :get, local: true, class: "search-form") do |f| %>
    <%= f.text_field :keyword, placeholder: "ギフトを検索", class: "search-input" %>
    <%= f.submit "検索", class: "search-btn" %>
  <% end %>

  <% @gifts.each do |gift| %>
    <%= render partial: "gift", locals: { gift: gift } %>
  <% end %>
</div>

app/views/gifts/new.html.erb
<div class="contents row">
  <div class="container">
    <h2>新規登録</h2>
    <%= render partial: "form", locals: { gift: @gift } %>    
  </div>
</div>

app/views/gifts/search.html.erb
<div class="contents row">
  <p class="sub_title">ギフト記録</p>
  <%= form_with(url: search_gifts_path, local: true, method: :get, class: "search-form") do |f| %>
    <%= f.text_field :keyword, placeholder: "ギフトを検索", class: "search-input" %>
    <%= f.submit "検索", class: "search-btn" %>
  <% end %>

  <% @gifts.each do |gift| %>
    <%= render partial: "gift", locals: { gift: gift } %>
  <% end %>
</div>

app/views/gifts/show.html.erb
<div class="contents row">
  <p class="sub_title">ギフト記録詳細</p>
    <div class="content_post ">
      <% if @gift.status_id == 2 %>
        <div class="status_a"><%= @gift.status.name %></div>
      <% else %>
        <div class="status_b"><%= @gift.status.name %></div>
      <%end%>
      <div><strong><%= @gift.name %></strong></div>
      <%= image_tag @gift.image.variant(resize: '500x500'), class: 'gift-image' if @gift.image.attached? %>
      <div><%= @gift.event_date&.strftime('%Y/%m/%d') %>
      <div><%= @gift.partner %></div>
      <div><%= @gift.event %></div>
      <div><%= safe_join(@gift.memo.split("\n"),tag(:br)) %></div>
    </div>
    <%= link_to '編集', edit_gift_path(@gift.id), class: "sub btn_a" %>
    <%= link_to '削除', gift_path(@gift.id), method: :delete, class: "sub btn_a", data: { confirm: 'この記録を削除しますか？' } %>
</div>

app/views/interests/_form.html.erb
<%= form_with(model: interest, local: true) do |f| %>
  
  <%= render 'layouts/error_messages', model: f.object %>

  <%= f.text_field :name, placeholder: "ギフトアイデアの名称" %>
  <%= f.file_field :image %>
  <div id="image-list"></div>
  <%= f.text_area :memo, placeholder: "メモ", rows: "10" %>
  <%= f.submit "登録" %>
<% end %>

app/views/interests/_interest.html.erb
<% if current_user.id == interest.user_id %>
<div class="content_post">
  <%= link_to interest_path(interest.id), class: "sub" do %>
    <%= image_tag interest.image.variant(resize: '400x400'), class: 'interest-image' if interest.image.attached? %>
    <div><strong><%= interest.name %></strong></div>
    <div><%= safe_join(interest.memo.split("\n"),tag(:br)) %></div>
  <% end %>
</div>
<% end %>

app/views/interests/edit.html.erb
<div class="contents row">
  <div class="container">
    <h2>編集</h2>
    <%= render partial: "form", locals: { interest: @interest } %>    
  </div>
</div>

app/views/interests/index.html.erb
<div class="contents row">
  <p class="sub_title">ギフトアイデア</p>
  <%= form_with(url: search_interests_path, method: :get, local: true, class: "search-form") do |f| %>
    <%= f.text_field :keyword, placeholder: "ギフトアイデアを検索", class: "search-input" %>
    <%= f.submit "検索", class: "search-btn" %>
  <% end %>

   <% @interests.each do |interest| %>
    <%= render partial: "interest", locals: { interest: interest } %>
   <% end %>
</div>

app/views/interests/new.html.erb
<div class="contents row">
  <div class="container">
    <h2>新規登録</h2>
    <%= render partial: "form", locals: { interest: @interest } %>
  </div>
</div>

app/views/interests/search.html.erb
<div class="contents row">
  <p class="sub_title">ギフトアイデア</p>
  <%= form_with(url: search_interests_path, local: true, method: :get, class: "search-form") do |f| %>
    <%= f.text_field :keyword, placeholder: "ギフトアイデアを検索", class: "search-input" %>
    <%= f.submit "検索", class: "search-btn" %>
  <% end %>

   <% @interests.each do |interest| %>
    <%= render partial: "interest", locals: { interest: interest } %>
   <% end %>
</div>

app/views/interests/show.html.erb
<div class="contents row">
  <p class="sub_title">ギフトアイデア詳細</p>
    <div class="content_post">
      <%= image_tag @interest.image.variant(resize: '500x500'), class: 'interest-image' if @interest.image.attached? %>
      <div><strong><%= @interest.name %></strong></div>
      <div><%= safe_join(@interest.memo.split("\n"),tag(:br)) %></div>
    <%= link_to '編集', edit_interest_path(@interest.id), class: "sub btn_a" %>
    <%= link_to '削除', interest_path(@interest.id), method: :delete, class: "sub btn_a", data: { confirm: 'この記録を削除しますか？' } %>
    </div>
</div>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |f| %>

  <%= render 'layouts/error_messages', model: f.object %>

  <%= f.text_field :name, placeholder: "商品名" %>
  <%= f.file_field :image %>
  <div id="image-list"></div>
  <%= f.text_field :price, placeholder: "金額" %>
  <%= f.text_area :memo, placeholder: "メモ", rows: "10" %>
  <%= f.text_field :shop, placeholder: "店名" %>
  <%= f.text_area :shopinfo, placeholder: "店情報・URL", rows: "10" %>
  <%= f.submit "登録" %>
<% end %>

app/views/items/_item.html.erb
<div class="content_post" >
  <%= image_tag item.image.variant(resize: '500x500'), class: 'item-image' if item.image.attached? %>
  <div><strong><%= item.name %></strong></div>
  <div><%= item.price %>円(税込)</div>
  <div><%= safe_join(item.memo.split("\n"),tag(:br)) %></div>
  <div><%= item.shop %></div>
  <div><%= safe_join(item.shopinfo.split("\n"),tag(:br)) %></div>
</div>

app/views/items/edit.html.erb
<div class="contents row">
  <div class="container">
    <h2>編集</h2>
    <%= render partial: "form", locals: { item: @item } %>    
  </div>
</div>

app/views/items/index.html.erb
<div class ="contents row">
  <p class="sub_title">お薦めギフト</p>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to "商品登録", new_item_path, class: "sub btn_a" %>
<% end %>

  <%= form_with(url: search_items_path, method: :get, local: true, class: "search-form") do |f| %>
    <%= f.text_field :keyword, placeholder: "ギフトを検索", class: "search-input" %>
    <%= f.submit "検索", class: "search-btn" %>
  <% end %>

   <% @items.each do |item| %>
    <%= render partial: "item", locals: { item: item } %>

    <% if user_signed_in? && current_user.admin? %>
    <div class="line_spase" >
      <%= link_to "編集", edit_item_path(item.id), class: "sub btn_b" %>
      <%= link_to '削除', item_path(item.id), method: :delete, class: "sub btn_b", data: { confirm: 'この記録を削除しますか？' } %>
    </div>
    <% end %>
   <% end %>
</div>

app/views/items/new.html.erb
<div class="contents row">
  <div class="container">
    <h2>新規登録</h2>
    <%= render partial: "form", locals: { item: @item } %>    
  </div>
</div>

app/views/items/search.html.erb
<div class ="contents row">
  <p class="sub_title">お薦めギフト</p>

  <%= form_with(url: search_items_path, method: :get, local: true, class: "search-form") do |f| %>
    <%= f.text_field :keyword, placeholder: "ギフトを検索", class: "search-input" %>
    <%= f.submit "検索", class: "search-btn" %>
  <% end %>

   <% @items.each do |item| %>
    <%= render partial: "item", locals: { item: item } %>
   <% end %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GiftLife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class="header">
      <div class="row">
        <h1 class="grid nav"><a href="/">GiftLife</a></h1>
        <% if user_signed_in? && current_page?(gifts_path)%>
          <div class="grid">
            <%= link_to "登録", new_gift_path, class: "nav" %>
            <%= link_to "アイデア", interests_path, class: "nav" %>            
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav" %>
          </div>

        <% elsif user_signed_in? && current_page?(interests_path)%>
          <div class="grid">
            <%= link_to "登録", new_interest_path, class: "nav" %>
            <%= link_to "ギフト記録", gifts_path, class: "nav" %>            
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav" %>
          </div>

        <% elsif user_signed_in? %>
          <div class="grid">
            <%= link_to "ギフト記録", gifts_path, class: "nav" %>
            <%= link_to "アイデア", interests_path, class: "nav" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav" %>
          </div>

        <% else %>
          <div class="grid">
            <%= link_to "ログイン", new_user_session_path, class: "nav" %>
            <%= link_to "新規登録", new_user_registration_path, class: "nav" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <p>
        Copyright GiftLife 2021.
      </p>
    </footer>
  </body>
</html>